### ISSUE TITLE
Doclet failes with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by olegshtch** [gboersma/uml-java-doclet#8]
I'm trying to generate documentation and gets error with version 1.0.0 published on the Central:

```
javadoc: error - In doclet class info.leadinglight.umljavadoclet.UmlJavaDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at info.leadinglight.umljavadoclet.model.ModelPackage.parentPackageFullName(ModelPackage.java:62)
	at info.leadinglight.umljavadoclet.model.Model.isRootPackage(Model.java:87)
	at info.leadinglight.umljavadoclet.model.Model.rootPackages(Model.java:75)
	at info.leadinglight.umljavadoclet.printer.OverviewDiagramPrinter.generate(OverviewDiagramPrinter.java:20)
	at info.leadinglight.umljavadoclet.UmlJavaDoclet.generateOverviewDiagram(UmlJavaDoclet.java:173)
	at info.leadinglight.umljavadoclet.UmlJavaDoclet.start(UmlJavaDoclet.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
	at com.sun.tools.javadoc.Start.begin(Start.java:219)
	at com.sun.tools.javadoc.Start.begin(Start.java:205)
	at com.sun.tools.javadoc.Main.execute(Main.java:64)
	at com.sun.tools.javadoc.Main.main(Main.java:54)
```

**Comment by gboersma** [comment]
Merged the pull request.
